version: 2
jobs:
  check_version:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - run:
          name: Check version number has been properly updated
          command: |
            git fetch
            .circleci/is-version-number-acceptable.sh

  build:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/openfisca_core
            python -m venv /tmp/venv/openfisca_core

      - run:
          name: Activate virtualenv
          command: echo "source /tmp/venv/openfisca_core/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install --requirement requirements/dev
            # pip install --editable git+https://github.com/openfisca/country-template.git@BRANCH_NAME#egg=OpenFisca-Country-Template  # use a specific branch of OpenFisca-Country-Template
            # pip install --editable git+https://github.com/openfisca/extension-template.git@BRANCH_NAME#egg=OpenFisca-Extension-Template  # use a specific branch of OpenFisca-Extension-Template

      - save_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/openfisca_core

  test:
    docker:
      - image: python:3.7

    environment:
      PYTEST_ADDOPTS: --exitfirst

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Activate virtualenv
          command: echo "source /tmp/venv/openfisca_core/bin/activate" >> $BASH_ENV

      - run:
          name: Install core
          command: pip install --editable .[dev] --upgrade --use-deprecated=legacy-resolver

      - run:
          name: Run core tests
          command: make test

      - persist_to_workspace:
          root: .
          paths:
            - .coverage

      - run:
          name: Run country template tests
          command: |
            COUNTRY_TEMPLATE_PATH=`python -c "import openfisca_country_template; print(openfisca_country_template.CountryTaxBenefitSystem().get_package_metadata()['location'])"`
            openfisca test $COUNTRY_TEMPLATE_PATH/openfisca_country_template/tests/

  test_constrained:
    docker:
      - image: python:3.7

    environment:
      PYTEST_ADDOPTS: --exitfirst

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Activate virtualenv
          command: echo "source /tmp/venv/openfisca_core/bin/activate" >> $BASH_ENV

      - run:
          name: Install core constrained
          command: pip install --editable .[dev] --upgrade --constraint requirements/constraints --use-deprecated=legacy-resolver

      - run:
          name: Run core tests
          command: make test

  submit_coverage:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - attach_workspace:
          at: .

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Submit coverage to Coveralls
          command: |
            source /tmp/venv/openfisca_core/bin/activate
            pip install --editable .[coverage]
            coveralls

      - save_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/openfisca_core

  deploy:
    docker:
      - image: python:3.7

    environment:
      PYPI_USERNAME: openfisca-bot
      # PYPI_PASSWORD: this value is set in CircleCI's web interface; do not set it here, it is a secret!

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Check for functional changes
          command: if ! .circleci/has-functional-changes.sh ; then circleci step halt ; fi

      - run:
          name: Activate virtualenv
          command: echo "source /tmp/venv/openfisca_core/bin/activate" >> $BASH_ENV

      - run:
          name: Upload a Python package to PyPi
          command: |
            pip install --editable .[publication]
            .circleci/publish-python-package.sh

      - run:
          name: Publish a git tag
          command: .circleci/publish-git-tag.sh

      - run:
          name: Update doc
          command: |
            curl -X POST --header "Content-Type: application/json" -d '{"branch":"master"}' https://circleci.com/api/v1.1/project/github/openfisca/openfisca-doc/build?circle-token=$CIRCLE_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - check_version
      - build
      - test:
          requires:
            - build
      - test_constrained:
          requires:
            - build
      - submit_coverage:
          requires:
            - test
            - test_constrained
      - deploy:
          requires:
            - check_version
            - test
            - test_constrained
          filters:
            branches:
              only: master
