version: 2
jobs:
  run_tests:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/openfisca_core
            python -m venv /tmp/venv/openfisca_core
            echo "source /tmp/venv/openfisca_core/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            make install
            # pip install --editable git+https://github.com/openfisca/country-template.git@BRANCH_NAME#egg=OpenFisca-Country-Template  # use a specific branch of OpenFisca-Country-Template
            # pip install --editable git+https://github.com/openfisca/extension-template.git@BRANCH_NAME#egg=OpenFisca-Extension-Template  # use a specific branch of OpenFisca-Extension-Template

      - save_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/openfisca_core

      - run:
          name: Run Core tests
          command: env PYTEST_ADDOPTS="--exitfirst" make test

      - run:
          name: Check NumPy typing against latest 3 minor versions
          command: for i in {1..3}; do VERSION=$(.circleci/get-numpy-version.py prev) && pip install numpy==$VERSION && make check-types; done

      - persist_to_workspace:
          root: .
          paths:
            - .coverage

      - run:
          name: Run Country Template tests
          command: |
            COUNTRY_TEMPLATE_PATH=`python -c "import openfisca_country_template; print(openfisca_country_template.CountryTaxBenefitSystem().get_package_metadata()['location'])"`
            openfisca test $COUNTRY_TEMPLATE_PATH/openfisca_country_template/tests/

  check_version:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - run:
          name: Check version number has been properly updated
          command: |
            git fetch
            .circleci/is-version-number-acceptable.sh

  submit_coverage:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - attach_workspace:
          at: .

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Submit coverage to Coveralls
          command: |
            source /tmp/venv/openfisca_core/bin/activate
            pip install --editable .[coverage]
            coveralls

      - save_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/openfisca_core

  deploy:
    docker:
      - image: python:3.7
    environment:
      PYPI_USERNAME: openfisca-bot
      # PYPI_PASSWORD: this value is set in CircleCI's web interface; do not set it here, it is a secret!

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Check for functional changes
          command: if ! .circleci/has-functional-changes.sh ; then circleci step halt ; fi

      - run:
          name: Upload a Python package to PyPi
          command: |
            source /tmp/venv/openfisca_core/bin/activate
            pip install --editable .[publication]
            .circleci/publish-python-package.sh

      - run:
          name: Publish a git tag
          command: .circleci/publish-git-tag.sh

      - run:
          name: Update doc
          command: |
            curl -X POST --header "Content-Type: application/json" -d '{"branch":"master"}' https://circleci.com/api/v1.1/project/github/openfisca/openfisca-doc/build?circle-token=$CIRCLE_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - run_tests
      - check_version
      - submit_coverage:
          requires:
            - run_tests
      - deploy:
          requires:
            - run_tests
            - check_version
          filters:
            branches:
              only: master
